### ISSUE TITLE
Download bug

### ISSUE THREAD

**Issue by egorsmkv** [huydx/hget#1]
```
~/Music — hget http://www.ex.ua/load/43539311
INFO: Resolve ip: 186.2.163.200
INFO: Download target size: 447.1 MB
43539311-0 208.06 MB / 111.77 MB [==================================================================================================================================================] 186.15% -40s
43539311-1 621 B / 111.77 MB [>--------------------------------------------------------------------------------------------------------------------------------------------------------]   0.00% 0
43539311-2 621 B / 111.77 MB [>--------------------------------------------------------------------------------------------------------------------------------------------------------]   0.00% 0
43539311-3 621 B / 111.77 MB [>--------------------------------------------------------------------------------------------------------------------------------------------------------]   0.00% 0
```

**Comment by huydx** [comment]
Hi @egorsmkv , thanks for report, it seems that the server's not fully support multi-stream download, I will fix that to fall back to single stream download.

**Comment by mcqueenorama** [comment]
Cool tool.

Maybe the same thing here:

L-SB831WYFD5-M:Downloads bmcquee$ hget https://services.gradle.org/distributions/gradle-3.0-bin.zip
INFO: Resolve ip: 207.223.250.8
INFO: Download target size: 66.1 MB
gradle-3.0-bin.zip-0 12.30 MB / 8.26 MB [=======================================================================] 148.84% -1m30s
gradle-3.0-bin.zip-1 12.56 MB / 8.26 MB [=======================================================================] 152.05% -1m33s
gradle-3.0-bin.zip-2 12.87 MB / 8.26 MB [=======================================================================] 155.83% -1m37s
gradle-3.0-bin.zip-3 12.61 MB / 8.26 MB [=======================================================================] 152.62% -1m34s
gradle-3.0-bin.zip-4 12.81 MB / 8.26 MB [=======================================================================] 155.08% -1m37s
gradle-3.0-bin.zip-5 11.23 MB / 8.26 MB [=======================================================================] 135.97% -1m12s
gradle-3.0-bin.zip-6 12.22 MB / 8.26 MB [=======================================================================] 147.89% -1m28s
gradle-3.0-bin.zip-7 13.47 MB / 8.26 MB [=======================================================================] 163.02% -1m46s
