### ISSUE TITLE
STDOUT no longer works after running

### ISSUE THREAD

**Issue by colejhudson** [huydx/hget#12]
After running ./hget commands are able to be executed, but nothing is visibly typed in. Likely because STDOUT (EDITED) is being redirected to some subshell or process created by hget. I'm running OSX 10.11.1 and have version 1.5.3 of go

**Comment by huydx** [comment]
you mean STDOUT? Currently hget output is just directed to STDOUT, what do you mean by `are able to executed`.

**Comment by Cole-Hudson** [comment]
Ha! Yah I did mean STDOUT, my bad. To clear up my ambiguity, what I mean by 'commands' were shell utilities, like 'ls', 'cd', etc. So for example, if I run hget, its execution completes perfectly, however nothing else can be printed to the terminal. So if I type in 'whoami' nothing appears while I'm typing, but if I hit enter the utility executes normally and displays the current user. I've included a recording below so you can see what I mean. 

![tty](https://cloud.githubusercontent.com/assets/11510882/17916221/28977298-6966-11e6-8875-56b9fef4a5ad.gif)

**Comment by colejhudson** [comment]
Ha! Yah I did mean STDOUT, my bad. To clear up my ambiguity, what I mean by 'commands' were shell utilities, like 'ls', 'cd', etc. So for example, if I run hget, its execution completes perfectly, however nothing else can be printed to the terminal. So if I type in 'whoami' nothing appears while I'm typing, but if I hit enter the utility executes normally and displays the current user. I've included a recording below so you can see what I mean. At the end I type the same utility again, and you can see while it executes fine nothing was printed while I was typing

![tty](https://cloud.githubusercontent.com/assets/11510882/17916291/e274bb6c-6966-11e6-90bf-3beab119df8f.gif)

**Comment by moorereason** [comment]
I'm seeing the same behavior.  After running hget, I see my normal bash prompt, but keyboard input is not echoed back to the screen.  I can blindly type in a command at the prompt and press Enter and do see the output of the command and a new prompt.   @cyber-gr1zzly's screen capture matches what I'm seeing.

I suspect it's upstream in `pb`: https://github.com/cheggaaa/pb/blob/v1.0.7/pb_x.go#L73.

Using hget/master (03213a995aeb8f3a655dcca3cc55ca8cafe494a0) with go1.7.3 linux/amd64.
