### ISSUE TITLE
-n not work

### ISSUE THREAD

**Issue by mehranexpert** [huydx/hget#16]
i want it download with 5 connections but it download with 2 connections .

```
./hget https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.8.10.tar.xz -n 5
INFO: Resolve ip: 151.101.60.69
INFO: Start download with 2 connections 
INFO: Download target size: 87.7 MB
linux-4.8.10.tar.xz-0 800.15 KB / 43.86 MB [>--------------------]   1.78% 2m57s
linux-4.8.10.tar.xz-1 735.48 KB / 43.86 MB [>--------------------]   1.64% 3m13s
INFO: Interrupted, saving state ... 
```

**Comment by Mehran** [comment]
yes ,  seems -n not work

**Comment by kriyss** [comment]
`./hget [file_to_download] -n 2`  not works
`./hget -n 2 [file_to_download] ` works for me

**Comment by droideck** [comment]
Flags in Go have certain behavior. There is a quote from the [docs](https://golang.org/pkg/flag/):

> Flag parsing stops just before the first non-flag argument ("-" is a non-flag argument) or after the terminator "--".

So I suggest that it would not be fixed because of the Go package design.

**Comment by huydx** [comment]
so it seems that this is just usage problem, so i will close this issue

**Comment by zQueal** [comment]
[This is still an issue](https://github.com/huydx/hget/blob/master/main.go#L133:L139).

Even when running `hget --help` its indicated that it's acceptable to use the flags __after__ the URL.
