### ISSUE TITLE
I got this to work in Windows

### ISSUE THREAD

**Issue by skadimoolam** [huydx/hget#2]
I just followed the setup instructions in the Readme file, there are some changes

Step 0: Setup `GOPATH` ENV in your machine
Step 1: `go get -d github.com/huydx/hget`
Step 2: `cd <GOPATH>/src/github.com/huydx/hget`   // Replace GOPATH with the actual path you set
Step 3: Edit Line 17 in the Makefile to be `go build -o 'hget.exe'`
Step 4: If you have `Make` installed you can use the command `make install` in the `hget` directory
Step 5: If you dont have `Make` you can execute these command one by one
- `go get -d github.com/fatih/color`
- `go get -d github.com/mattn/go-colorable`
- `go get -d github.com/mattn/go-isatty`
- `go get -d gopkg.in/cheggaaa/pb.v1`
- `go get -d github.com/fatih/color`
- `go build -o 'hget.exe'`

That's all.

**Comment by huydx** [comment]
@skadimoolam Thank you for your effort! However did you try to run all functions of hget on windows? It may be build-able but hget has some logic just work only on unix, for example get home directory by `os.Getenv("HOME")`

**Comment by KEANO89** [comment]
Is there any reason not to use "os/user" for getting the current user's home dir?

**Comment by skadimoolam** [comment]
@huydx You are right, it does not work, I forked this project and I have started to implement a fallback for windows.

**Comment by zQueal** [comment]
Confirmed __not__ working on Windows. Crosscompiled from source via `gox` to no avail.

![TNzcQNe](https://user-images.githubusercontent.com/239193/57551167-5dc30180-7336-11e9-90e1-3e85dde1ee2e.png)
