### ISSUE TITLE
tlsClient: No such file or directory

### ISSUE THREAD

**Issue by sunfmin** [huydx/hget#4]
```
Felix:actor sunfmin$ hget https://download.docker.com/mac/stable/Docker.dmg
tlsClient: No such file or directory
tlsClient: No such file or directory
tlsClient: No such file or directory
tlsClient: No such file or directory
tlsClient: No such file or directory
tlsClient: No such file or directory
tlsClient: No such file or directory
tlsClient: No such file or directory
tlsClient: No such file or directory
tlsClient: No such file or directory
tlsClient: No such file or directory
hget: too many errors with no progress No such file or directory

```

**Comment by huydx** [comment]
@sunfmin can you pull out newest version and see if that error persist?

**Comment by sunfmin** [comment]
Yes, It still exists, I just installed, I think I have the latest version.

![snip20160811_3](https://cloud.githubusercontent.com/assets/1014/17585218/0daf1698-5fed-11e6-8b93-f8e90f2ba22c.png)

**Comment by huydx** [comment]
Can you give me your os version, and how you install hget?

**Comment by sunfmin** [comment]
Sorry, I think my system confused me with plan9port's hget...

![snip20160811_4](https://cloud.githubusercontent.com/assets/1014/17585331/b3a45c5c-5fed-11e6-9d96-17f14a0371d5.png)

Just confirmed, it works fine with yours.
