### ISSUE TITLE
Support wget-like resume

### ISSUE THREAD

**Issue by anoldguy** [huydx/hget#6]
This is a fantastic tool, thank you!  

Is there any chance of supporting something like wget's continue flag?

```
wget -c http://foo.bar/baz
```

That will check for `baz` to continue, and if it exists, resume the transfer.  If it doesn't exist, it starts a new transfer.

Right now, I have to run `hget tasks` (or guess at the task name) and then run `hget resume taskname`.  I'd love to be able to just run `hget -c http://foo.bar/baz` (or `-r` or whatever) and have it look for an existing download to resume and help me out a bit.

Again, super minor niggle, this is a great tool. I'm easily able to saturate my connection! ❤️

**Comment by huydx** [comment]
@anoldguy nice suggestion, i will add in near future

**Comment by huydx** [comment]
I've support resume URL as well by this PR: https://github.com/huydx/hget/commit/03213a995aeb8f3a655dcca3cc55ca8cafe494a0
